// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameFollowList = "follow_list"

// FollowList 存放用户关注列表元信息
type FollowList struct {
	ListID   int64  `gorm:"column:list_id;type:bigint unsigned;primaryKey" json:"list_id"`
	ListName string `gorm:"column:list_name;type:varchar(20);not null;uniqueIndex:follow_list_user_id_list_name_uindex,priority:2" json:"list_name"`
	UserID   int64  `gorm:"column:user_id;type:bigint unsigned;not null;uniqueIndex:follow_list_user_id_list_name_uindex,priority:1" json:"user_id"`
}

// TableName FollowList's table name
func (*FollowList) TableName() string {
	return TableNameFollowList
}
