// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameUserFavorite = "user_favorites"

// UserFavorite 用户收藏夹表
type UserFavorite struct {
	FavoriteID   int64  `gorm:"column:favorite_id;type:bigint unsigned;primaryKey" json:"favorite_id"`
	UserID       int64  `gorm:"column:user_id;type:bigint unsigned;not null;uniqueIndex:user_favorites_user_id_favorite_name_uindex,priority:1" json:"user_id"`
	FavoriteName string `gorm:"column:favorite_name;type:varchar(50);not null;uniqueIndex:user_favorites_user_id_favorite_name_uindex,priority:2" json:"favorite_name"`
	Description  string `gorm:"column:description;type:text" json:"description"`
	IsPrivate    int64  `gorm:"column:is_private;type:int;default:1;comment:表示该收藏夹是否私密，1表示公开，-1表示私密" json:"is_private"` // 表示该收藏夹是否私密，1表示公开，-1表示私密
}

// TableName UserFavorite's table name
func (*UserFavorite) TableName() string {
	return TableNameUserFavorite
}
