// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"

	"gorm.io/gorm"
)

const TableNameUserFan = "user_fans"

// UserFan 用户粉丝表
type UserFan struct {
	UserID     int64          `gorm:"column:user_id;type:bigint unsigned;primaryKey" json:"user_id"`
	FollowerID int64          `gorm:"column:follower_id;type:bigint unsigned;primaryKey" json:"follower_id"`
	DeletedAt  gorm.DeletedAt `gorm:"column:deleted_at;type:datetime(3);index:user_followed_deletedAt,priority:1" json:"deleted_at"`
	UpdatedAt  time.Time      `gorm:"column:updated_at;type:datetime(3);not null" json:"updated_at"`
	CreatedAt  time.Time      `gorm:"column:created_at;type:datetime(3);not null" json:"created_at"`
}

// TableName UserFan's table name
func (*UserFan) TableName() string {
	return TableNameUserFan
}
