// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"

	"gorm.io/gorm"
)

const TableNameUserFollow = "user_follows"

// UserFollow 存放用户关注的用户的id
type UserFollow struct {
	FollowlistID int64          `gorm:"column:followlist_id;type:bigint unsigned;not null" json:"followlist_id"`
	FollowUserID int64          `gorm:"column:follow_user_id;type:int;primaryKey;comment:被关注的用户id" json:"follow_user_id"` // 被关注的用户id
	UserID       int64          `gorm:"column:user_id;type:bigint unsigned;primaryKey" json:"user_id"`
	UpdatedAt    time.Time      `gorm:"column:updated_at;type:datetime(3);not null" json:"updated_at"`
	DeletedAt    gorm.DeletedAt `gorm:"column:deleted_at;type:datetime(3);index:user_follows_deletedAt,priority:1" json:"deleted_at"`
	CreatedAt    time.Time      `gorm:"column:created_at;type:datetime(3);not null" json:"created_at"`
}

// TableName UserFollow's table name
func (*UserFollow) TableName() string {
	return TableNameUserFollow
}
