// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameUserLevel = "user_level"

// UserLevel mapped from table <user_level>
type UserLevel struct {
	UserID  int64  `gorm:"column:user_id;type:bigint unsigned;primaryKey" json:"user_id"`
	NextExp uint32 `gorm:"column:next_exp;type:int unsigned;not null;default:50;comment:升级到下一级所需总经验" json:"next_exp"` // 升级到下一级所需总经验
	Exp     uint32 `gorm:"column:exp;type:int unsigned;comment:当前已获得的经验值" json:"exp"`                                 // 当前已获得的经验值
	Level   uint32 `gorm:"column:level;type:int unsigned;not null" json:"level"`
}

func (level *UserLevel) AddExp(exp uint32) {
	level.Exp += exp
	if level.Exp >= level.NextExp {
		level.Exp = level.Exp - level.NextExp
		level.Level += 1
		level.NextExp = (level.Level + 1) * (level.Level + 5) * 10
	}
}

// TableName UserLevel's table name
func (*UserLevel) TableName() string {
	return TableNameUserLevel
}
