server:
  http:
    addr: 0.0.0.0:8002
    timeout: 10s
  grpc:
    addr: 0.0.0.0:9002
    timeout: 10s
data:
  elastic:
    addr: https://127.0.0.1:9200
    username: <Username>
    password: <PASSWORD>
  mysql:
    driver: mysql
    source: root:<PASSWORD>@tcp(127.0.0.1:3306)/kratos_demo_shop_goods?parseTime=True&loc=Local
    max_idle: 10
    max_open: 100
  redis:
    addr: 127.0.0.1:6379
    password: "<PASSWORD>"
    db: 0
    dial_timeout: 1s
    read_timeout: 0.2s
    write_timeout: 0.2s
trace:    # 链路追踪参数
  endpoint: http://127.0.0.1:14268/api/traces
