// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"
	"database/sql"

	"gorm.io/gorm"

	"gorm.io/gen"

	"gorm.io/plugin/dbresolver"
)

var (
	Q            = new(Query)
	FollowList   *followList
	User         *user
	UserFan      *userFan
	UserFavorite *userFavorite
	UserFollow   *userFollow
	UserLevel    *userLevel
)

func SetDefault(db *gorm.DB, opts ...gen.DOOption) {
	*Q = *Use(db, opts...)
	FollowList = &Q.FollowList
	User = &Q.User
	UserFan = &Q.UserFan
	UserFavorite = &Q.UserFavorite
	UserFollow = &Q.UserFollow
	UserLevel = &Q.UserLevel
}

func Use(db *gorm.DB, opts ...gen.DOOption) *Query {
	return &Query{
		db:           db,
		FollowList:   newFollowList(db, opts...),
		User:         newUser(db, opts...),
		UserFan:      newUserFan(db, opts...),
		UserFavorite: newUserFavorite(db, opts...),
		UserFollow:   newUserFollow(db, opts...),
		UserLevel:    newUserLevel(db, opts...),
	}
}

type Query struct {
	db *gorm.DB

	FollowList   followList
	User         user
	UserFan      userFan
	UserFavorite userFavorite
	UserFollow   userFollow
	UserLevel    userLevel
}

func (q *Query) Available() bool { return q.db != nil }

func (q *Query) clone(db *gorm.DB) *Query {
	return &Query{
		db:           db,
		FollowList:   q.FollowList.clone(db),
		User:         q.User.clone(db),
		UserFan:      q.UserFan.clone(db),
		UserFavorite: q.UserFavorite.clone(db),
		UserFollow:   q.UserFollow.clone(db),
		UserLevel:    q.UserLevel.clone(db),
	}
}

func (q *Query) ReadDB() *Query {
	return q.ReplaceDB(q.db.Clauses(dbresolver.Read))
}

func (q *Query) WriteDB() *Query {
	return q.ReplaceDB(q.db.Clauses(dbresolver.Write))
}

func (q *Query) ReplaceDB(db *gorm.DB) *Query {
	return &Query{
		db:           db,
		FollowList:   q.FollowList.replaceDB(db),
		User:         q.User.replaceDB(db),
		UserFan:      q.UserFan.replaceDB(db),
		UserFavorite: q.UserFavorite.replaceDB(db),
		UserFollow:   q.UserFollow.replaceDB(db),
		UserLevel:    q.UserLevel.replaceDB(db),
	}
}

type queryCtx struct {
	FollowList   IFollowListDo
	User         IUserDo
	UserFan      IUserFanDo
	UserFavorite IUserFavoriteDo
	UserFollow   IUserFollowDo
	UserLevel    IUserLevelDo
}

func (q *Query) WithContext(ctx context.Context) *queryCtx {
	return &queryCtx{
		FollowList:   q.FollowList.WithContext(ctx),
		User:         q.User.WithContext(ctx),
		UserFan:      q.UserFan.WithContext(ctx),
		UserFavorite: q.UserFavorite.WithContext(ctx),
		UserFollow:   q.UserFollow.WithContext(ctx),
		UserLevel:    q.UserLevel.WithContext(ctx),
	}
}

func (q *Query) Transaction(fc func(tx *Query) error, opts ...*sql.TxOptions) error {
	return q.db.Transaction(func(tx *gorm.DB) error { return fc(q.clone(tx)) }, opts...)
}

func (q *Query) Begin(opts ...*sql.TxOptions) *QueryTx {
	tx := q.db.Begin(opts...)
	return &QueryTx{Query: q.clone(tx), Error: tx.Error}
}

type QueryTx struct {
	*Query
	Error error
}

func (q *QueryTx) Commit() error {
	return q.db.Commit().Error
}

func (q *QueryTx) Rollback() error {
	return q.db.Rollback().Error
}

func (q *QueryTx) SavePoint(name string) error {
	return q.db.SavePoint(name).Error
}

func (q *QueryTx) RollbackTo(name string) error {
	return q.db.RollbackTo(name).Error
}
