// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.27.0
// source: goods/v1/goods.proto

package v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Goods_CreateCategory_FullMethodName           = "/api.goods.v1.Goods/CreateCategory"
	Goods_CreateGoodsType_FullMethodName          = "/api.goods.v1.Goods/CreateGoodsType"
	Goods_CreateGoodsSpecification_FullMethodName = "/api.goods.v1.Goods/CreateGoodsSpecification"
	Goods_CreateAttrGroup_FullMethodName          = "/api.goods.v1.Goods/CreateAttrGroup"
	Goods_CreateAttrValue_FullMethodName          = "/api.goods.v1.Goods/CreateAttrValue"
	Goods_CreateGoods_FullMethodName              = "/api.goods.v1.Goods/CreateGoods"
	Goods_GoodsList_FullMethodName                = "/api.goods.v1.Goods/GoodsList"
)

// GoodsClient is the client API for Goods service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type GoodsClient interface {
	CreateCategory(ctx context.Context, in *CreateCategoryReq, opts ...grpc.CallOption) (*CreateCategoryResp, error)
	CreateGoodsType(ctx context.Context, in *GoodsTypeReq, opts ...grpc.CallOption) (*GoodsTypeResp, error)
	// 商品规格或属性的信息
	CreateGoodsSpecification(ctx context.Context, in *SpecificationReq, opts ...grpc.CallOption) (*SpecificationResp, error)
	// 商品参数属性分组名
	CreateAttrGroup(ctx context.Context, in *CreateAttrGroupReq, opts ...grpc.CallOption) (*CreateAttrGroupResp, error)
	// 商品参数属性名和值
	CreateAttrValue(ctx context.Context, in *CreateAttrValueReq, opts ...grpc.CallOption) (*CreateAttrValueResp, error)
	// 创建商品
	CreateGoods(ctx context.Context, in *CreateGoodsReq, opts ...grpc.CallOption) (*CreateGoodsResp, error)
	// 通过elastic search查询商品
	GoodsList(ctx context.Context, in *GoodsListReq, opts ...grpc.CallOption) (*GoodsListResp, error)
}

type goodsClient struct {
	cc grpc.ClientConnInterface
}

func NewGoodsClient(cc grpc.ClientConnInterface) GoodsClient {
	return &goodsClient{cc}
}

func (c *goodsClient) CreateCategory(ctx context.Context, in *CreateCategoryReq, opts ...grpc.CallOption) (*CreateCategoryResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateCategoryResp)
	err := c.cc.Invoke(ctx, Goods_CreateCategory_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *goodsClient) CreateGoodsType(ctx context.Context, in *GoodsTypeReq, opts ...grpc.CallOption) (*GoodsTypeResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GoodsTypeResp)
	err := c.cc.Invoke(ctx, Goods_CreateGoodsType_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *goodsClient) CreateGoodsSpecification(ctx context.Context, in *SpecificationReq, opts ...grpc.CallOption) (*SpecificationResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SpecificationResp)
	err := c.cc.Invoke(ctx, Goods_CreateGoodsSpecification_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *goodsClient) CreateAttrGroup(ctx context.Context, in *CreateAttrGroupReq, opts ...grpc.CallOption) (*CreateAttrGroupResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateAttrGroupResp)
	err := c.cc.Invoke(ctx, Goods_CreateAttrGroup_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *goodsClient) CreateAttrValue(ctx context.Context, in *CreateAttrValueReq, opts ...grpc.CallOption) (*CreateAttrValueResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateAttrValueResp)
	err := c.cc.Invoke(ctx, Goods_CreateAttrValue_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *goodsClient) CreateGoods(ctx context.Context, in *CreateGoodsReq, opts ...grpc.CallOption) (*CreateGoodsResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateGoodsResp)
	err := c.cc.Invoke(ctx, Goods_CreateGoods_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *goodsClient) GoodsList(ctx context.Context, in *GoodsListReq, opts ...grpc.CallOption) (*GoodsListResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GoodsListResp)
	err := c.cc.Invoke(ctx, Goods_GoodsList_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// GoodsServer is the server API for Goods service.
// All implementations must embed UnimplementedGoodsServer
// for forward compatibility.
type GoodsServer interface {
	CreateCategory(context.Context, *CreateCategoryReq) (*CreateCategoryResp, error)
	CreateGoodsType(context.Context, *GoodsTypeReq) (*GoodsTypeResp, error)
	// 商品规格或属性的信息
	CreateGoodsSpecification(context.Context, *SpecificationReq) (*SpecificationResp, error)
	// 商品参数属性分组名
	CreateAttrGroup(context.Context, *CreateAttrGroupReq) (*CreateAttrGroupResp, error)
	// 商品参数属性名和值
	CreateAttrValue(context.Context, *CreateAttrValueReq) (*CreateAttrValueResp, error)
	// 创建商品
	CreateGoods(context.Context, *CreateGoodsReq) (*CreateGoodsResp, error)
	// 通过elastic search查询商品
	GoodsList(context.Context, *GoodsListReq) (*GoodsListResp, error)
	mustEmbedUnimplementedGoodsServer()
}

// UnimplementedGoodsServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedGoodsServer struct{}

func (UnimplementedGoodsServer) CreateCategory(context.Context, *CreateCategoryReq) (*CreateCategoryResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateCategory not implemented")
}
func (UnimplementedGoodsServer) CreateGoodsType(context.Context, *GoodsTypeReq) (*GoodsTypeResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateGoodsType not implemented")
}
func (UnimplementedGoodsServer) CreateGoodsSpecification(context.Context, *SpecificationReq) (*SpecificationResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateGoodsSpecification not implemented")
}
func (UnimplementedGoodsServer) CreateAttrGroup(context.Context, *CreateAttrGroupReq) (*CreateAttrGroupResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateAttrGroup not implemented")
}
func (UnimplementedGoodsServer) CreateAttrValue(context.Context, *CreateAttrValueReq) (*CreateAttrValueResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateAttrValue not implemented")
}
func (UnimplementedGoodsServer) CreateGoods(context.Context, *CreateGoodsReq) (*CreateGoodsResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateGoods not implemented")
}
func (UnimplementedGoodsServer) GoodsList(context.Context, *GoodsListReq) (*GoodsListResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GoodsList not implemented")
}
func (UnimplementedGoodsServer) mustEmbedUnimplementedGoodsServer() {}
func (UnimplementedGoodsServer) testEmbeddedByValue()               {}

// UnsafeGoodsServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to GoodsServer will
// result in compilation errors.
type UnsafeGoodsServer interface {
	mustEmbedUnimplementedGoodsServer()
}

func RegisterGoodsServer(s grpc.ServiceRegistrar, srv GoodsServer) {
	// If the following call pancis, it indicates UnimplementedGoodsServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Goods_ServiceDesc, srv)
}

func _Goods_CreateCategory_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateCategoryReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GoodsServer).CreateCategory(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Goods_CreateCategory_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GoodsServer).CreateCategory(ctx, req.(*CreateCategoryReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Goods_CreateGoodsType_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GoodsTypeReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GoodsServer).CreateGoodsType(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Goods_CreateGoodsType_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GoodsServer).CreateGoodsType(ctx, req.(*GoodsTypeReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Goods_CreateGoodsSpecification_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SpecificationReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GoodsServer).CreateGoodsSpecification(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Goods_CreateGoodsSpecification_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GoodsServer).CreateGoodsSpecification(ctx, req.(*SpecificationReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Goods_CreateAttrGroup_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateAttrGroupReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GoodsServer).CreateAttrGroup(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Goods_CreateAttrGroup_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GoodsServer).CreateAttrGroup(ctx, req.(*CreateAttrGroupReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Goods_CreateAttrValue_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateAttrValueReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GoodsServer).CreateAttrValue(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Goods_CreateAttrValue_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GoodsServer).CreateAttrValue(ctx, req.(*CreateAttrValueReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Goods_CreateGoods_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateGoodsReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GoodsServer).CreateGoods(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Goods_CreateGoods_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GoodsServer).CreateGoods(ctx, req.(*CreateGoodsReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Goods_GoodsList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GoodsListReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GoodsServer).GoodsList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Goods_GoodsList_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GoodsServer).GoodsList(ctx, req.(*GoodsListReq))
	}
	return interceptor(ctx, in, info, handler)
}

// Goods_ServiceDesc is the grpc.ServiceDesc for Goods service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Goods_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "api.goods.v1.Goods",
	HandlerType: (*GoodsServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateCategory",
			Handler:    _Goods_CreateCategory_Handler,
		},
		{
			MethodName: "CreateGoodsType",
			Handler:    _Goods_CreateGoodsType_Handler,
		},
		{
			MethodName: "CreateGoodsSpecification",
			Handler:    _Goods_CreateGoodsSpecification_Handler,
		},
		{
			MethodName: "CreateAttrGroup",
			Handler:    _Goods_CreateAttrGroup_Handler,
		},
		{
			MethodName: "CreateAttrValue",
			Handler:    _Goods_CreateAttrValue_Handler,
		},
		{
			MethodName: "CreateGoods",
			Handler:    _Goods_CreateGoods_Handler,
		},
		{
			MethodName: "GoodsList",
			Handler:    _Goods_GoodsList_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "goods/v1/goods.proto",
}
