// Code generated by protoc-gen-validate. DO NOT EDIT.
// source: goods/v1/goods.proto

package v1

import (
	"bytes"
	"errors"
	"fmt"
	"net"
	"net/mail"
	"net/url"
	"regexp"
	"sort"
	"strings"
	"time"
	"unicode/utf8"

	"google.golang.org/protobuf/types/known/anypb"
)

// ensure the imports are used
var (
	_ = bytes.MinRead
	_ = errors.New("")
	_ = fmt.Print
	_ = utf8.UTFMax
	_ = (*regexp.Regexp)(nil)
	_ = (*strings.Reader)(nil)
	_ = net.IPv4len
	_ = time.Duration(0)
	_ = (*url.URL)(nil)
	_ = (*mail.Address)(nil)
	_ = anypb.Any{}
	_ = sort.Sort
)

// Validate checks the field values on CreateCategoryReq with the rules defined
// in the proto definition for this message. If any rules are violated, the
// first error encountered is returned, or nil if there are no violations.
func (m *CreateCategoryReq) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on CreateCategoryReq with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// CreateCategoryReqMultiError, or nil if none found.
func (m *CreateCategoryReq) ValidateAll() error {
	return m.validate(true)
}

func (m *CreateCategoryReq) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Id

	// no validation rules for Name

	// no validation rules for ParentCategory

	// no validation rules for Level

	// no validation rules for IsTab

	// no validation rules for Sort

	if len(errors) > 0 {
		return CreateCategoryReqMultiError(errors)
	}

	return nil
}

// CreateCategoryReqMultiError is an error wrapping multiple validation errors
// returned by CreateCategoryReq.ValidateAll() if the designated constraints
// aren't met.
type CreateCategoryReqMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m CreateCategoryReqMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m CreateCategoryReqMultiError) AllErrors() []error { return m }

// CreateCategoryReqValidationError is the validation error returned by
// CreateCategoryReq.Validate if the designated constraints aren't met.
type CreateCategoryReqValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e CreateCategoryReqValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e CreateCategoryReqValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e CreateCategoryReqValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e CreateCategoryReqValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e CreateCategoryReqValidationError) ErrorName() string {
	return "CreateCategoryReqValidationError"
}

// Error satisfies the builtin error interface
func (e CreateCategoryReqValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sCreateCategoryReq.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = CreateCategoryReqValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = CreateCategoryReqValidationError{}

// Validate checks the field values on CreateCategoryResp with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *CreateCategoryResp) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on CreateCategoryResp with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// CreateCategoryRespMultiError, or nil if none found.
func (m *CreateCategoryResp) ValidateAll() error {
	return m.validate(true)
}

func (m *CreateCategoryResp) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Id

	// no validation rules for Name

	// no validation rules for ParentCategory

	// no validation rules for Level

	// no validation rules for IsTab

	// no validation rules for Sort

	if len(errors) > 0 {
		return CreateCategoryRespMultiError(errors)
	}

	return nil
}

// CreateCategoryRespMultiError is an error wrapping multiple validation errors
// returned by CreateCategoryResp.ValidateAll() if the designated constraints
// aren't met.
type CreateCategoryRespMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m CreateCategoryRespMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m CreateCategoryRespMultiError) AllErrors() []error { return m }

// CreateCategoryRespValidationError is the validation error returned by
// CreateCategoryResp.Validate if the designated constraints aren't met.
type CreateCategoryRespValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e CreateCategoryRespValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e CreateCategoryRespValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e CreateCategoryRespValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e CreateCategoryRespValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e CreateCategoryRespValidationError) ErrorName() string {
	return "CreateCategoryRespValidationError"
}

// Error satisfies the builtin error interface
func (e CreateCategoryRespValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sCreateCategoryResp.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = CreateCategoryRespValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = CreateCategoryRespValidationError{}

// Validate checks the field values on GoodsTypeReq with the rules defined in
// the proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *GoodsTypeReq) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on GoodsTypeReq with the rules defined
// in the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in GoodsTypeReqMultiError, or
// nil if none found.
func (m *GoodsTypeReq) ValidateAll() error {
	return m.validate(true)
}

func (m *GoodsTypeReq) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Id

	if utf8.RuneCountInString(m.GetName()) < 1 {
		err := GoodsTypeReqValidationError{
			field:  "Name",
			reason: "value length must be at least 1 runes",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if utf8.RuneCountInString(m.GetTypeCode()) < 3 {
		err := GoodsTypeReqValidationError{
			field:  "TypeCode",
			reason: "value length must be at least 3 runes",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	// no validation rules for AliasName

	// no validation rules for IsVirtual

	// no validation rules for Desc

	// no validation rules for Sort

	if len(errors) > 0 {
		return GoodsTypeReqMultiError(errors)
	}

	return nil
}

// GoodsTypeReqMultiError is an error wrapping multiple validation errors
// returned by GoodsTypeReq.ValidateAll() if the designated constraints aren't met.
type GoodsTypeReqMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m GoodsTypeReqMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m GoodsTypeReqMultiError) AllErrors() []error { return m }

// GoodsTypeReqValidationError is the validation error returned by
// GoodsTypeReq.Validate if the designated constraints aren't met.
type GoodsTypeReqValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e GoodsTypeReqValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e GoodsTypeReqValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e GoodsTypeReqValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e GoodsTypeReqValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e GoodsTypeReqValidationError) ErrorName() string { return "GoodsTypeReqValidationError" }

// Error satisfies the builtin error interface
func (e GoodsTypeReqValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sGoodsTypeReq.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = GoodsTypeReqValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = GoodsTypeReqValidationError{}

// Validate checks the field values on GoodsTypeResp with the rules defined in
// the proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *GoodsTypeResp) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on GoodsTypeResp with the rules defined
// in the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in GoodsTypeRespMultiError, or
// nil if none found.
func (m *GoodsTypeResp) ValidateAll() error {
	return m.validate(true)
}

func (m *GoodsTypeResp) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Id

	if len(errors) > 0 {
		return GoodsTypeRespMultiError(errors)
	}

	return nil
}

// GoodsTypeRespMultiError is an error wrapping multiple validation errors
// returned by GoodsTypeResp.ValidateAll() if the designated constraints
// aren't met.
type GoodsTypeRespMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m GoodsTypeRespMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m GoodsTypeRespMultiError) AllErrors() []error { return m }

// GoodsTypeRespValidationError is the validation error returned by
// GoodsTypeResp.Validate if the designated constraints aren't met.
type GoodsTypeRespValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e GoodsTypeRespValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e GoodsTypeRespValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e GoodsTypeRespValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e GoodsTypeRespValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e GoodsTypeRespValidationError) ErrorName() string { return "GoodsTypeRespValidationError" }

// Error satisfies the builtin error interface
func (e GoodsTypeRespValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sGoodsTypeResp.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = GoodsTypeRespValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = GoodsTypeRespValidationError{}

// Validate checks the field values on SpecificationReq with the rules defined
// in the proto definition for this message. If any rules are violated, the
// first error encountered is returned, or nil if there are no violations.
func (m *SpecificationReq) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on SpecificationReq with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// SpecificationReqMultiError, or nil if none found.
func (m *SpecificationReq) ValidateAll() error {
	return m.validate(true)
}

func (m *SpecificationReq) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Id

	if m.GetTypeId() <= 0 {
		err := SpecificationReqValidationError{
			field:  "TypeId",
			reason: "value must be greater than 0",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if utf8.RuneCountInString(m.GetName()) < 1 {
		err := SpecificationReqValidationError{
			field:  "Name",
			reason: "value length must be at least 1 runes",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	// no validation rules for Sort

	// no validation rules for Status

	// no validation rules for IsSku

	// no validation rules for IsSelect

	for idx, item := range m.GetSpecificationValues() {
		_, _ = idx, item

		if all {
			switch v := interface{}(item).(type) {
			case interface{ ValidateAll() error }:
				if err := v.ValidateAll(); err != nil {
					errors = append(errors, SpecificationReqValidationError{
						field:  fmt.Sprintf("SpecificationValues[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			case interface{ Validate() error }:
				if err := v.Validate(); err != nil {
					errors = append(errors, SpecificationReqValidationError{
						field:  fmt.Sprintf("SpecificationValues[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			}
		} else if v, ok := interface{}(item).(interface{ Validate() error }); ok {
			if err := v.Validate(); err != nil {
				return SpecificationReqValidationError{
					field:  fmt.Sprintf("SpecificationValues[%v]", idx),
					reason: "embedded message failed validation",
					cause:  err,
				}
			}
		}

	}

	if len(errors) > 0 {
		return SpecificationReqMultiError(errors)
	}

	return nil
}

// SpecificationReqMultiError is an error wrapping multiple validation errors
// returned by SpecificationReq.ValidateAll() if the designated constraints
// aren't met.
type SpecificationReqMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m SpecificationReqMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m SpecificationReqMultiError) AllErrors() []error { return m }

// SpecificationReqValidationError is the validation error returned by
// SpecificationReq.Validate if the designated constraints aren't met.
type SpecificationReqValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e SpecificationReqValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e SpecificationReqValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e SpecificationReqValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e SpecificationReqValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e SpecificationReqValidationError) ErrorName() string { return "SpecificationReqValidationError" }

// Error satisfies the builtin error interface
func (e SpecificationReqValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sSpecificationReq.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = SpecificationReqValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = SpecificationReqValidationError{}

// Validate checks the field values on SpecificationResp with the rules defined
// in the proto definition for this message. If any rules are violated, the
// first error encountered is returned, or nil if there are no violations.
func (m *SpecificationResp) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on SpecificationResp with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// SpecificationRespMultiError, or nil if none found.
func (m *SpecificationResp) ValidateAll() error {
	return m.validate(true)
}

func (m *SpecificationResp) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Id

	if len(errors) > 0 {
		return SpecificationRespMultiError(errors)
	}

	return nil
}

// SpecificationRespMultiError is an error wrapping multiple validation errors
// returned by SpecificationResp.ValidateAll() if the designated constraints
// aren't met.
type SpecificationRespMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m SpecificationRespMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m SpecificationRespMultiError) AllErrors() []error { return m }

// SpecificationRespValidationError is the validation error returned by
// SpecificationResp.Validate if the designated constraints aren't met.
type SpecificationRespValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e SpecificationRespValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e SpecificationRespValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e SpecificationRespValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e SpecificationRespValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e SpecificationRespValidationError) ErrorName() string {
	return "SpecificationRespValidationError"
}

// Error satisfies the builtin error interface
func (e SpecificationRespValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sSpecificationResp.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = SpecificationRespValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = SpecificationRespValidationError{}

// Validate checks the field values on CreateAttrGroupReq with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *CreateAttrGroupReq) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on CreateAttrGroupReq with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// CreateAttrGroupReqMultiError, or nil if none found.
func (m *CreateAttrGroupReq) ValidateAll() error {
	return m.validate(true)
}

func (m *CreateAttrGroupReq) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Id

	if m.GetTypeId() < 1 {
		err := CreateAttrGroupReqValidationError{
			field:  "TypeId",
			reason: "value must be greater than or equal to 1",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if utf8.RuneCountInString(m.GetTitle()) < 1 {
		err := CreateAttrGroupReqValidationError{
			field:  "Title",
			reason: "value length must be at least 1 runes",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	// no validation rules for Desc

	// no validation rules for Status

	if m.GetSort() < 1 {
		err := CreateAttrGroupReqValidationError{
			field:  "Sort",
			reason: "value must be greater than or equal to 1",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if len(errors) > 0 {
		return CreateAttrGroupReqMultiError(errors)
	}

	return nil
}

// CreateAttrGroupReqMultiError is an error wrapping multiple validation errors
// returned by CreateAttrGroupReq.ValidateAll() if the designated constraints
// aren't met.
type CreateAttrGroupReqMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m CreateAttrGroupReqMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m CreateAttrGroupReqMultiError) AllErrors() []error { return m }

// CreateAttrGroupReqValidationError is the validation error returned by
// CreateAttrGroupReq.Validate if the designated constraints aren't met.
type CreateAttrGroupReqValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e CreateAttrGroupReqValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e CreateAttrGroupReqValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e CreateAttrGroupReqValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e CreateAttrGroupReqValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e CreateAttrGroupReqValidationError) ErrorName() string {
	return "CreateAttrGroupReqValidationError"
}

// Error satisfies the builtin error interface
func (e CreateAttrGroupReqValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sCreateAttrGroupReq.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = CreateAttrGroupReqValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = CreateAttrGroupReqValidationError{}

// Validate checks the field values on CreateAttrGroupResp with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *CreateAttrGroupResp) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on CreateAttrGroupResp with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// CreateAttrGroupRespMultiError, or nil if none found.
func (m *CreateAttrGroupResp) ValidateAll() error {
	return m.validate(true)
}

func (m *CreateAttrGroupResp) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Id

	// no validation rules for TypeId

	// no validation rules for Title

	// no validation rules for Desc

	// no validation rules for Status

	// no validation rules for Sort

	if len(errors) > 0 {
		return CreateAttrGroupRespMultiError(errors)
	}

	return nil
}

// CreateAttrGroupRespMultiError is an error wrapping multiple validation
// errors returned by CreateAttrGroupResp.ValidateAll() if the designated
// constraints aren't met.
type CreateAttrGroupRespMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m CreateAttrGroupRespMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m CreateAttrGroupRespMultiError) AllErrors() []error { return m }

// CreateAttrGroupRespValidationError is the validation error returned by
// CreateAttrGroupResp.Validate if the designated constraints aren't met.
type CreateAttrGroupRespValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e CreateAttrGroupRespValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e CreateAttrGroupRespValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e CreateAttrGroupRespValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e CreateAttrGroupRespValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e CreateAttrGroupRespValidationError) ErrorName() string {
	return "CreateAttrGroupRespValidationError"
}

// Error satisfies the builtin error interface
func (e CreateAttrGroupRespValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sCreateAttrGroupResp.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = CreateAttrGroupRespValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = CreateAttrGroupRespValidationError{}

// Validate checks the field values on CreateAttrValueReq with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *CreateAttrValueReq) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on CreateAttrValueReq with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// CreateAttrValueReqMultiError, or nil if none found.
func (m *CreateAttrValueReq) ValidateAll() error {
	return m.validate(true)
}

func (m *CreateAttrValueReq) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Id

	if m.GetTypeId() < 1 {
		err := CreateAttrValueReqValidationError{
			field:  "TypeId",
			reason: "value must be greater than or equal to 1",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if m.GetGroupId() < 1 {
		err := CreateAttrValueReqValidationError{
			field:  "GroupId",
			reason: "value must be greater than or equal to 1",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if utf8.RuneCountInString(m.GetTitle()) < 1 {
		err := CreateAttrValueReqValidationError{
			field:  "Title",
			reason: "value length must be at least 1 runes",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	// no validation rules for Desc

	// no validation rules for Status

	if m.GetSort() < 1 {
		err := CreateAttrValueReqValidationError{
			field:  "Sort",
			reason: "value must be greater than or equal to 1",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	for idx, item := range m.GetAttrValue() {
		_, _ = idx, item

		if all {
			switch v := interface{}(item).(type) {
			case interface{ ValidateAll() error }:
				if err := v.ValidateAll(); err != nil {
					errors = append(errors, CreateAttrValueReqValidationError{
						field:  fmt.Sprintf("AttrValue[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			case interface{ Validate() error }:
				if err := v.Validate(); err != nil {
					errors = append(errors, CreateAttrValueReqValidationError{
						field:  fmt.Sprintf("AttrValue[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			}
		} else if v, ok := interface{}(item).(interface{ Validate() error }); ok {
			if err := v.Validate(); err != nil {
				return CreateAttrValueReqValidationError{
					field:  fmt.Sprintf("AttrValue[%v]", idx),
					reason: "embedded message failed validation",
					cause:  err,
				}
			}
		}

	}

	if len(errors) > 0 {
		return CreateAttrValueReqMultiError(errors)
	}

	return nil
}

// CreateAttrValueReqMultiError is an error wrapping multiple validation errors
// returned by CreateAttrValueReq.ValidateAll() if the designated constraints
// aren't met.
type CreateAttrValueReqMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m CreateAttrValueReqMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m CreateAttrValueReqMultiError) AllErrors() []error { return m }

// CreateAttrValueReqValidationError is the validation error returned by
// CreateAttrValueReq.Validate if the designated constraints aren't met.
type CreateAttrValueReqValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e CreateAttrValueReqValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e CreateAttrValueReqValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e CreateAttrValueReqValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e CreateAttrValueReqValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e CreateAttrValueReqValidationError) ErrorName() string {
	return "CreateAttrValueReqValidationError"
}

// Error satisfies the builtin error interface
func (e CreateAttrValueReqValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sCreateAttrValueReq.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = CreateAttrValueReqValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = CreateAttrValueReqValidationError{}

// Validate checks the field values on CreateAttrValueResp with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *CreateAttrValueResp) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on CreateAttrValueResp with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// CreateAttrValueRespMultiError, or nil if none found.
func (m *CreateAttrValueResp) ValidateAll() error {
	return m.validate(true)
}

func (m *CreateAttrValueResp) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Id

	// no validation rules for TypeId

	// no validation rules for GroupId

	// no validation rules for Title

	// no validation rules for Desc

	// no validation rules for Status

	// no validation rules for Sort

	for idx, item := range m.GetAttrValue() {
		_, _ = idx, item

		if all {
			switch v := interface{}(item).(type) {
			case interface{ ValidateAll() error }:
				if err := v.ValidateAll(); err != nil {
					errors = append(errors, CreateAttrValueRespValidationError{
						field:  fmt.Sprintf("AttrValue[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			case interface{ Validate() error }:
				if err := v.Validate(); err != nil {
					errors = append(errors, CreateAttrValueRespValidationError{
						field:  fmt.Sprintf("AttrValue[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			}
		} else if v, ok := interface{}(item).(interface{ Validate() error }); ok {
			if err := v.Validate(); err != nil {
				return CreateAttrValueRespValidationError{
					field:  fmt.Sprintf("AttrValue[%v]", idx),
					reason: "embedded message failed validation",
					cause:  err,
				}
			}
		}

	}

	if len(errors) > 0 {
		return CreateAttrValueRespMultiError(errors)
	}

	return nil
}

// CreateAttrValueRespMultiError is an error wrapping multiple validation
// errors returned by CreateAttrValueResp.ValidateAll() if the designated
// constraints aren't met.
type CreateAttrValueRespMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m CreateAttrValueRespMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m CreateAttrValueRespMultiError) AllErrors() []error { return m }

// CreateAttrValueRespValidationError is the validation error returned by
// CreateAttrValueResp.Validate if the designated constraints aren't met.
type CreateAttrValueRespValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e CreateAttrValueRespValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e CreateAttrValueRespValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e CreateAttrValueRespValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e CreateAttrValueRespValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e CreateAttrValueRespValidationError) ErrorName() string {
	return "CreateAttrValueRespValidationError"
}

// Error satisfies the builtin error interface
func (e CreateAttrValueRespValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sCreateAttrValueResp.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = CreateAttrValueRespValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = CreateAttrValueRespValidationError{}

// Validate checks the field values on SpecificationReq_SpecificationValue with
// the rules defined in the proto definition for this message. If any rules
// are violated, the first error encountered is returned, or nil if there are
// no violations.
func (m *SpecificationReq_SpecificationValue) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on SpecificationReq_SpecificationValue
// with the rules defined in the proto definition for this message. If any
// rules are violated, the result is a list of violation errors wrapped in
// SpecificationReq_SpecificationValueMultiError, or nil if none found.
func (m *SpecificationReq_SpecificationValue) ValidateAll() error {
	return m.validate(true)
}

func (m *SpecificationReq_SpecificationValue) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Id

	// no validation rules for AttrId

	if utf8.RuneCountInString(m.GetValue()) < 3 {
		err := SpecificationReq_SpecificationValueValidationError{
			field:  "Value",
			reason: "value length must be at least 3 runes",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	// no validation rules for Sort

	if len(errors) > 0 {
		return SpecificationReq_SpecificationValueMultiError(errors)
	}

	return nil
}

// SpecificationReq_SpecificationValueMultiError is an error wrapping multiple
// validation errors returned by
// SpecificationReq_SpecificationValue.ValidateAll() if the designated
// constraints aren't met.
type SpecificationReq_SpecificationValueMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m SpecificationReq_SpecificationValueMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m SpecificationReq_SpecificationValueMultiError) AllErrors() []error { return m }

// SpecificationReq_SpecificationValueValidationError is the validation error
// returned by SpecificationReq_SpecificationValue.Validate if the designated
// constraints aren't met.
type SpecificationReq_SpecificationValueValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e SpecificationReq_SpecificationValueValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e SpecificationReq_SpecificationValueValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e SpecificationReq_SpecificationValueValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e SpecificationReq_SpecificationValueValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e SpecificationReq_SpecificationValueValidationError) ErrorName() string {
	return "SpecificationReq_SpecificationValueValidationError"
}

// Error satisfies the builtin error interface
func (e SpecificationReq_SpecificationValueValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sSpecificationReq_SpecificationValue.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = SpecificationReq_SpecificationValueValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = SpecificationReq_SpecificationValueValidationError{}

// Validate checks the field values on CreateAttrValueReq_AttrValue with the
// rules defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *CreateAttrValueReq_AttrValue) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on CreateAttrValueReq_AttrValue with the
// rules defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// CreateAttrValueReq_AttrValueMultiError, or nil if none found.
func (m *CreateAttrValueReq_AttrValue) ValidateAll() error {
	return m.validate(true)
}

func (m *CreateAttrValueReq_AttrValue) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Id

	// no validation rules for AttrId

	// no validation rules for GroupId

	if utf8.RuneCountInString(m.GetValue()) < 3 {
		err := CreateAttrValueReq_AttrValueValidationError{
			field:  "Value",
			reason: "value length must be at least 3 runes",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if len(errors) > 0 {
		return CreateAttrValueReq_AttrValueMultiError(errors)
	}

	return nil
}

// CreateAttrValueReq_AttrValueMultiError is an error wrapping multiple
// validation errors returned by CreateAttrValueReq_AttrValue.ValidateAll() if
// the designated constraints aren't met.
type CreateAttrValueReq_AttrValueMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m CreateAttrValueReq_AttrValueMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m CreateAttrValueReq_AttrValueMultiError) AllErrors() []error { return m }

// CreateAttrValueReq_AttrValueValidationError is the validation error returned
// by CreateAttrValueReq_AttrValue.Validate if the designated constraints
// aren't met.
type CreateAttrValueReq_AttrValueValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e CreateAttrValueReq_AttrValueValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e CreateAttrValueReq_AttrValueValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e CreateAttrValueReq_AttrValueValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e CreateAttrValueReq_AttrValueValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e CreateAttrValueReq_AttrValueValidationError) ErrorName() string {
	return "CreateAttrValueReq_AttrValueValidationError"
}

// Error satisfies the builtin error interface
func (e CreateAttrValueReq_AttrValueValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sCreateAttrValueReq_AttrValue.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = CreateAttrValueReq_AttrValueValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = CreateAttrValueReq_AttrValueValidationError{}

// Validate checks the field values on CreateAttrValueResp_AttrValue with the
// rules defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *CreateAttrValueResp_AttrValue) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on CreateAttrValueResp_AttrValue with
// the rules defined in the proto definition for this message. If any rules
// are violated, the result is a list of violation errors wrapped in
// CreateAttrValueResp_AttrValueMultiError, or nil if none found.
func (m *CreateAttrValueResp_AttrValue) ValidateAll() error {
	return m.validate(true)
}

func (m *CreateAttrValueResp_AttrValue) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Id

	// no validation rules for AttrId

	// no validation rules for GroupId

	// no validation rules for Value

	if len(errors) > 0 {
		return CreateAttrValueResp_AttrValueMultiError(errors)
	}

	return nil
}

// CreateAttrValueResp_AttrValueMultiError is an error wrapping multiple
// validation errors returned by CreateAttrValueResp_AttrValue.ValidateAll()
// if the designated constraints aren't met.
type CreateAttrValueResp_AttrValueMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m CreateAttrValueResp_AttrValueMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m CreateAttrValueResp_AttrValueMultiError) AllErrors() []error { return m }

// CreateAttrValueResp_AttrValueValidationError is the validation error
// returned by CreateAttrValueResp_AttrValue.Validate if the designated
// constraints aren't met.
type CreateAttrValueResp_AttrValueValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e CreateAttrValueResp_AttrValueValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e CreateAttrValueResp_AttrValueValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e CreateAttrValueResp_AttrValueValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e CreateAttrValueResp_AttrValueValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e CreateAttrValueResp_AttrValueValidationError) ErrorName() string {
	return "CreateAttrValueResp_AttrValueValidationError"
}

// Error satisfies the builtin error interface
func (e CreateAttrValueResp_AttrValueValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sCreateAttrValueResp_AttrValue.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = CreateAttrValueResp_AttrValueValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = CreateAttrValueResp_AttrValueValidationError{}
