// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/go-kratos/kratos/v2"
	"github.com/go-kratos/kratos/v2/log"
	"goods/internal/biz"
	"goods/internal/conf"
	"goods/internal/data"
	"goods/internal/server"
	"goods/internal/service"
)

import (
	_ "go.uber.org/automaxprocs"
)

// Injectors from wire.go:

// wireApp init kratos application.
func wireApp(confServer *conf.Server, confData *conf.Data, registry *conf.Registry, logger log.Logger) (*kratos.App, func(), error) {
	db := data.NewMySQL(confData)
	client := data.NewRedis(confData)
	dataData, cleanup, err := data.NewData(confData, db, client, logger)
	if err != nil {
		return nil, nil, err
	}
	categoryRepo := data.NewCategoryRepo(dataData, logger)
	categoryUsecase := biz.NewCategoryUsecase(categoryRepo, logger)
	goodsTypeRepo := data.NewGoodsTypeRepo(dataData, logger)
	transaction := data.NewTransaction(dataData)
	goodsTypeUsecase := biz.NewGoodsTypeUsecase(goodsTypeRepo, transaction, logger)
	goodsAttrRepo := data.NewGoodsAttrRepo(dataData, logger)
	goodsAttrUsecase := biz.NewGoodsAttrUsecase(goodsAttrRepo, goodsTypeRepo, transaction, logger)
	specificationRepo := data.NewSpecificationRepo(dataData, logger)
	specificationUsecase := biz.NewSpecificationUsecase(specificationRepo, goodsTypeRepo, transaction, logger)
	goodsService := service.NewGoodsService(categoryUsecase, goodsTypeUsecase, goodsAttrUsecase, specificationUsecase, logger)
	grpcServer := server.NewGRPCServer(confServer, goodsService, logger)
	registrar := server.NewRegistrar(registry)
	app := newApp(logger, grpcServer, registrar)
	return app, func() {
		cleanup()
	}, nil
}
